name: collect

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: collect content
        run: make collect
      - name: commit content
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No updates found"
          else
            echo "Updates found"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m "updated at `date`"
            git push
          fi